name: CI

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_dispatch: 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user torch --extra-index-url https://download.pytorch.org/whl/cu117/
        pip install flake8 pytest
        python setup.py install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest tests
